source "https://rubygems.org"
ruby "3.3.0"

gem "rails", "~> 7.1.0"
gem "pg", "~> 1.1"
gem "puma", ">= 5.0"
gem "redis", ">= 4.0.1"

group :development, :test do
  gem "rspec-rails"
  gem "rubocop-rails"
end
